repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    # This version should align with what's installed in your environment
    rev: v0.4.4
    hooks:
        # Run the linter first (important when using --fix)
        - id: ruff
          args: [--fix, --exit-non-zero-on-fix]
        # Run the formatter after the linter
        - id: ruff-format

-   repo: https://github.com/pre-commit/mirrors-mypy
    # Mypy version defined in pyproject.toml
    rev: 'v1.15.0' # Pin to a specific tag, check compatibility with your mypy version
    hooks:
    -   id: mypy
        # args: [--strict] # Can add args here, but prefer config in pyproject.toml
        additional_dependencies: [
            # Add any necessary Mypy plugins here if not managed elsewhere
            "pydantic", # Ensure pydantic types are available to mypy hook
            "pydantic-settings", # BaseSettings typing
            "sqlalchemy[mypy]", # Ensure sqlalchemy stubs/plugin are available
            "mypy==1.15.0"
            ]

-   repo: https://github.com/PyCQA/bandit
    # Bandit version defined in pyproject.toml
    rev: '1.8.3' # Pin to a specific tag, check compatibility
    hooks:
    -   id: bandit
        args: ["-c", "pyproject.toml"] # Use config from pyproject.toml
        # Pass baseline argument if using baselining: args: ["-b", "bandit_baseline.json"]
        additional_dependencies: ["bandit[toml]"] # Need this for pyproject.toml config

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files # Prevents giant files from being committed
      - id: check-yaml              # Validates all YAML files
      - id: check-toml              # Validates all TOML files
      - id: check-merge-conflict    # Check for files containing merge conflict strings
      - id: trailing-whitespace     # Removes trailing whitespace
      - id: end-of-file-fixer       # Ensures files end with a newline
      - id: debug-statements        # Check for debugger imports and py37+ breakpoint()
      - id: detect-private-key      # Detects private keys
