# ruff.toml
# Harmonise with black's (PEP 8) *or* project style – we raise it a bit
# so docstrings & URLs fit without ugly wrapping.
line-length = 120
target-version = "py312"

[lint]
# Update to use current rule codes
select = ["E", "W", "F", "I", "UP", "D", "S", "B", "A", "C4", "T20", "SIM", "PTH", "N", "ASYNC1", "FLY", "PERF", "RUF"]
ignore = [
    "D100", "D101", "D102", "D103", "D104", "D105", "D106", "D107", # Ignore missing docstring errors
    "S101", # Ignore assert statements
    "D213", # disable second-line summary rule so that our summary (D212) works as desired
    "D203", # Explicitly ignore one-blank-line-before-class in favor of D211
]

[lint.per-file-ignores]
# FastAPI routers use dependency injection patterns that trigger B008
"**/router.py" = ["B008"]
"**/routers/*.py" = ["B008"]

# Test files need more relaxed rules for common test patterns
"tests/**/*.py" = [
    "S101",     # Allow assert statements in tests
    "PLR2004",  # Allow magic values in tests
    "S105",     # Allow hardcoded passwords in tests
    "S106",     # Allow hardcoded passwords in tests
    "ARG001",   # Allow unused function arguments (fixtures)
    "ARG002",   # Allow unused method arguments
    "FBT001",   # Allow boolean positional args in tests
    "FBT002",   # Allow boolean default args in tests
    "PLC0415",  # Allow import outside top-level in tests
    "TRY301",   # Allow simple raise statements in tests
    "D100", "D101", "D102", "D103", "D104", "D105", "D106", "D107", # No docstrings required in tests
]

[format]
# No specific format settings needed if defaults are fine
