"""init cc tables.

Revision ID: ef3c881c1d43
Revises:
Create Date: 2025-05-17 20:25:12.058707

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ef3c881c1d43"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "health_status",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("module", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("last_updated", sa.DateTime(), nullable=False),
        sa.Column("details", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="cc",
    )
    op.create_index(
        op.f("ix_cc_health_status_module"),
        "health_status",
        ["module"],
        unique=True,
        schema="cc",
    )
    op.create_table(
        "modules",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("version", sa.String(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("last_active", sa.DateTime(), nullable=False),
        sa.Column("config", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="cc",
    )
    op.create_index(
        op.f("ix_cc_modules_name"), "modules", ["name"], unique=True, schema="cc"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_cc_modules_name"), table_name="modules", schema="cc")
    op.drop_table("modules", schema="cc")
    op.drop_index(
        op.f("ix_cc_health_status_module"), table_name="health_status", schema="cc"
    )
    op.drop_table("health_status", schema="cc")
    # ### end Alembic commands ###
