services:
  neo4j:
    restart: always
    image: neo4j:2025.04.0 # Community Edition with new datacode 2025.04.0 format
    container_name: cos_neo4j
    environment:
      NEO4J_AUTH: ${NEO4J_USER}/${NEO4J_PASSWORD}
      NEO4J_dbms_memory_pagecache_size: 2G
      NEO4J_dbms_memory_heap_initial__size: 2G
      NEO4J_dbms_memory_heap_max__size: 2G
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - type: bind
        source: F:/neo4j_cos_data
        target: /data
      - type: bind
        source: F:/neo4j_cos_logs
        target: /logs
      - type: bind
        source: F:/neo4j_cos_transactions
        target: /var/lib/neo4j/transactions
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.neo4j.rule=Host(`neo4j.cos.local`)"
      - "traefik.http.routers.neo4j.entrypoints=web"
      - "traefik.http.services.neo4j.loadbalancer.server.port=7474"
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "7"
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:7474 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - cos_network

networks:
  cos_network:
    external: true
    name: cos_network

# Note: mem0g service removed - will be implemented in Phase 2 with actual Mem0 architecture
# This keeps Neo4j running for L2 graph layer development while avoiding placeholder failures
