services:
  postgres_prod:
    image: postgres:17.5-bookworm
    container_name: cos_postgres_prod
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_PROD}
      POSTGRES_DB: ${POSTGRES_DB_PROD}
    ports:
      - "5432:5432"
    volumes:
      - type: bind
        source: ${COS_POSTGRES_ROOT}_prod
        target: /var/lib/postgresql/data
    # Resource limits - Soft limits (reservations) with higher limits
    # For MacBook Air M4 (24GB): 2GB typical, 3GB max
    # For Mac Studio M4 Max (128GB): 8GB typical, 12GB max
    deploy:
      resources:
        limits:
          cpus: "4"      # Max 4 CPU cores (half of M4's 8 cores)
          memory: 3G     # Hard limit: 3GB for MacBook Air
        reservations:
          cpus: "2"      # Reserve 2 CPU cores
          memory: 2G     # Reserve 2GB RAM (soft limit)
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: 'json-file'
      options:
        max-size: "10m"
        max-file: "3"

  postgres_dev:
    image: postgres:17.5-bookworm
    container_name: cos_postgres_dev
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_DEV}
      POSTGRES_DB: ${POSTGRES_DB_DEV}
    ports:
      - "5433:5432"
    volumes:
      - type: bind
        source: ${COS_POSTGRES_ROOT}_dev
        target: /var/lib/postgresql/data
    # Resource limits - Lower than prod since it's for development
    # For MacBook Air M4 (24GB): 1GB typical, 2GB max
    # For Mac Studio M4 Max (128GB): 4GB typical, 8GB max
    deploy:
      resources:
        limits:
          cpus: "2"      # Max 2 CPU cores for dev
          memory: 2G     # Hard limit: 2GB for MacBook Air
        reservations:
          cpus: "1"      # Reserve 1 CPU core
          memory: 1G     # Reserve 1GB RAM (soft limit)
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: 'json-file'
      options:
        max-size: "10m"
        max-file: "3"


  redis:
    restart: always
    image: redis/redis-stack:latest # Use :latest for dev only; PIN version in production!
    container_name: cos_redis
    ports:
      - "${REDIS_PORT}:6379"
      - "8001:8001"
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - type: bind
        source: ${COS_REDIS_ROOT}
        target: /data
      - type: bind
        source: ./redis.conf
        target: /usr/local/etc/redis/redis.conf
    environment:
      # The requirepass in redis.conf already uses ${REDIS_PASSWORD}
      # No need to set REDIS_ARGS or REDIS_PASSWORD here if conf file handles it.
      # If redis.conf wasn't using it, you'd do:
      # REDIS_ARGS: --requirepass ${REDIS_PASSWORD}
      # For clarity, ensure redis.conf IS using ${REDIS_PASSWORD} from the environment.
      # Docker Compose passes .env variables to the container's environment,
      # and redis.conf can substitute them if it's processed by an entrypoint script
      # or if Redis itself supports env var substitution in its config file loading.
      # A common pattern is for the Redis image's entrypoint to handle this.
      # If not, you might need to use `env_file: .env` directly in the service definition
      # OR ensure the command explicitly passes it if the conf file cannot substitute.
      # For redis/redis-stack, simply having REDIS_PASSWORD in the container's env
      # and `requirepass ${REDIS_PASSWORD}` in redis.conf should work as the image
      # often has an entrypoint script that processes the .conf file.
      # For safety, you can add:
      REDIS_PASSWORD: ${REDIS_PASSWORD} # Makes it available to entrypoint scripts
    # Resource limits - Redis is memory-intensive but CPU-light
    # For MacBook Air M4 (24GB): 512MB typical, 1GB max
    # For Mac Studio M4 Max (128GB): 2GB typical, 4GB max
    deploy:
      resources:
        limits:
          cpus: "2"      # Max 2 CPU cores (Redis is mostly single-threaded)
          memory: 1G     # Hard limit: 1GB for MacBook Air
        reservations:
          cpus: "0.5"    # Reserve 0.5 CPU core
          memory: 512M   # Reserve 512MB RAM (soft limit)
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    logging:
      driver: 'json-file'
      options:
        max-size: "10m"
        max-file: "3"

  elasticsearch:
    restart: unless-stopped
    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.2
    container_name: cos_elasticsearch
    environment:
      - discovery.type=single-node
      # Adjust ES_JAVA_OPTS based on available memory
      # For MacBook Air M4: Use 2G heap (within 3G container limit)
      # For Mac Studio M4 Max: Use 4G heap (within 6G container limit)
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
    ports:
      - "9200:9200"
    volumes:
      - type: bind
        source: ${COS_ELASTICSEARCH_ROOT}
        target: /usr/share/elasticsearch/data
    # Resource limits - Elasticsearch is memory and CPU intensive
    # For MacBook Air M4 (24GB): 2G typical, 3G max
    # For Mac Studio M4 Max (128GB): 4G typical, 6G max
    deploy:
      resources:
        limits:
          cpus: "4"      # Max 4 CPU cores
          memory: 3G     # Hard limit: 3GB for MacBook Air (includes JVM heap + overhead)
        reservations:
          cpus: "2"      # Reserve 2 CPU cores
          memory: 2G     # Reserve 2GB RAM (soft limit)
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Placeholder for backend container
  # (Currently building the 'cc' module — later integrate backend server here)

  # Placeholder for frontend and shared OpenAPI logic
  # TODO: Should frontend/backend share OpenAPI via volume or generated schema?
  # IDE/Agent decision point: depends on workflow (Next.js vs FastAPI-only vs gateway)

volumes:
  pg_test_data:

networks:
  cos_network:
    driver: bridge
    # Uncomment below for custom subnet if needed
    # ipam:
    #   config:
    #     - subnet: 172.28.0.0/16
